name: Deploy Laravel ke cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy file ke server via FTP
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Memaksa runner menggunakan Node.js 24 modern
    steps:
    - name: 🚚 Mengambil kode terbaru dari github
      uses: actions/checkout@v4 # Diperbarui dari v3 ke v4
      with:
        fetch-depth: 0

    - name: 📂 Sinkronisasi File ke cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        - name: 📂 Sinkronisasi File ke cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21  # Menegaskan port FTP standar sesuai data cPanel kamu
        server-dir: /
        state-name: .ftp-deploy-sync-state.json # Membantu melacak file yang sukses terupload
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/tests/**
          .env